trigger:
- main

stages:
- stage: BuildPushDeploy
  jobs:
  - job: AppDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: 'yourapp/repo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'

    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: '$(azureSubscriptionServiceConnection)'
        azureResourceGroup: 'dev-aks-rg'
        kubernetesCluster: 'dev-aks'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'manifests/deployment.yaml'